management:
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
    git:
      mode: "full"
  endpoint:
    health:
      show-components: always
      #show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: thespeace-actuator
    company: thespeace

logging:
  level:
    thespeace.controller: debug


server:
  tomcat:
    mbeanregistry:
      enabled: true